import './style.css';
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';
const supabase = SUPABASE_URL && SUPABASE_KEY ? createClient(SUPABASE_URL, SUPABASE_KEY) : null;

const R = [
 {id:'hoffmann-v60',name:'Ultimate V60',creator:'James Hoffmann',badge:'Signature',method:'Pour Over',coffee_g:30,water_g:500,ratio:16.7,grind:'Medium-fine',temperature_c:97,brew_seconds:210,notes:'60g bloom, two main pours, final bed-settle.',sourceUrl:'https://www.hario-usa.com/blogs/recipes-and-more-from-friends/james-hoffmann-uitimate-v60',steps:[['Bloom',45,'Pour to 60g and swirl gently.','60g','Wet every ground.'],['First pour',75,'Pour steadily to 300g.','300g','Keep the flow smooth.'],['Finish water',105,'Pour more gently to 500g.','500g','Keep the bed topped up.'],['Set the bed',120,'Stir once each way, then gently swirl.','—','Flatten the bed.'],['Drawdown',210,'Leave it to drain until the bed is flat.','—','Aim for 3:30 total.']]},
 {id:'hedrick-easy',name:'Easy & Effective V60',creator:'Lance Hedrick',badge:'High clarity',method:'Pour Over',coffee_g:20,water_g:340,ratio:17,grind:'Medium-fine',temperature_c:100,brew_seconds:210,notes:'Four pours with controlled spins.',sourceUrl:'https://www.youtube.com/watch?v=Ji4lZTtRAoo',steps:[['Bloom',30,'Pour 50g and spin.','50g','Boiling water is intentional.'],['Second pour',60,'Pour to 100g and spin.','100g','Keep the motion controlled.'],['Third pour',90,'Pour to 220g and spin.','220g','Aim just behind centre.'],['Final pour',120,'Pour to 340g and spin.','340g','One final controlled spin.'],['Drawdown',210,'Let the brew drain completely.','—','Typical finish 2:30–3:30.']]},
 {id:'rao-v60',name:'Rao Spin V60',creator:'Scott Rao',badge:'Precision',method:'Pour Over',coffee_g:22,water_g:360,ratio:16.4,grind:'Medium-fine',temperature_c:95,brew_seconds:180,notes:'Bloom agitation, one continuous main pour and a finishing spin.',sourceUrl:'https://www.scottrao.com/blog/2017/12/5/the-ideal-v60-technique',steps:[['Bloom',45,'Pour 66g and gently agitate.','66g','Even saturation is the goal.'],['Main pour',80,'Pour continuously to 360g.','360g','Keep a consistent stream.'],['Release walls',110,'Gently stir grounds away from the walls.','360g','Keep agitation gentle.'],['Rao spin + drawdown',180,'Gently spin to level the bed, then drain.','—','Finish around 3:00.']]},
 {id:'april-v60',name:'April Four-Pour',creator:'April Coffee Roasters',badge:'Bright & clean',method:'Pour Over',coffee_g:13,water_g:200,ratio:15.4,grind:'Medium-coarse',temperature_c:92,brew_seconds:150,notes:'Four equal pours at 30-second intervals.',sourceUrl:'https://www.aprilcoffeeroasters.com/pages/coffee-inf-recipes',steps:[['Pour one',30,'Pour to 50g.','50g','Establish an even bed.'],['Pour two',60,'Pour to 100g.','100g','Repeat the same motion.'],['Pour three',90,'Pour to 150g.','150g','Keep the flow consistent.'],['Pour four',120,'Pour to 200g.','200g','Finish without flooding.'],['Drawdown',150,'Let the coffee drain.','—','Aim for 2:30 total.']]}
];

const state={user:null,recipes:[],page:'home',timer:180,timerRunning:false,timerId:null,guide:null,guideLoop:null,shot:{elapsed:0,running:false,target:30,interval:null,dose:18,yield:36}};
const app=document.querySelector('#app');
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=s=>`${String(Math.floor(Math.max(0,s)/60)).padStart(2,'0')}:${String(Math.floor(Math.max(0,s)%60)).padStart(2,'0')}`;
const ratio=()=>{const c=+document.querySelector('#coffee')?.value||0,w=+document.querySelector('#water')?.value||0;return c?w/c:0};

function render(){
 app.innerHTML=`<div class="app-shell">
 <header class="topbar"><button class="menu-btn" id="menuBtn" aria-label="Open menu"><span></span><span></span></button><div class="brand"><div class="brand-mark"><span></span></div><div><div class="eyebrow">POCKET BARISTA</div><div class="brand-title">PB<span>01</span></div></div></div><button class="profile-btn" id="authBtn">${state.user?'●':'○'}</button></header>
 <main>
  ${state.page==='home'?homePage():state.page==='pour'?pourPage():espressoPage()}
 </main>
 <nav class="bottom-nav"><button class="${state.page==='home'?'active':''}" data-page="home"><b>⌂</b><span>Dashboard</span></button><button class="${state.page==='pour'?'active':''}" data-page="pour"><b>◒</b><span>Pour Over</span></button><button class="${state.page==='espresso'?'active':''}" data-page="espresso"><b>◉</b><span>Espresso</span></button><button id="navMenu"><b>≡</b><span>Menu</span></button></nav>
 <div id="modal"></div></div>`;
 bind();
}

function homePage(){return `<section class="dashboard-head"><div><div class="eyebrow">COFFEE CONTROL / 01</div><h1>Good coffee.<br><em>Precisely made.</em></h1><p>Everything you need to brew, time and dial in — in one quiet workspace.</p></div><div class="status-chip"><i></i> SYSTEM READY</div></section>
<section class="command-grid">
 <button class="command-card hero-command" data-page="pour"><div class="command-icon pour-icon">◒</div><div class="command-copy"><span>METHOD 01</span><h2>Pour Over</h2><p>Guided recipes · live step countdown · scale targets</p></div><b>→</b></button>
 <button class="command-card" data-page="espresso"><div class="command-icon">◉</div><div class="command-copy"><span>METHOD 02</span><h2>Espresso</h2><p>Shot timer · dose · yield · ratio</p></div><b>→</b></button>
</section>
<section class="dashboard-grid"><div class="panel spotlight"><div class="panel-top"><span class="eyebrow">TODAY'S FEATURE</span><span class="micro">GUIDED</span></div><div class="spotlight-art"><div class="dial"><span>V60</span><strong>01</strong></div><div class="beam"></div></div><div><span class="recipe-badge">${esc(R[0].badge)}</span><h2>${esc(R[0].name)}</h2><p>${esc(R[0].creator)} · ${R[0].coffee_g}g / ${R[0].water_g}g · 1:${R[0].ratio}</p></div><button class="primary wide" data-brew="${R[0].id}">Launch guided brew <span>↗</span></button></div>
 <div class="panel metrics"><div class="panel-top"><span class="eyebrow">BREW INTELLIGENCE</span><span class="micro">LIVE</span></div><div class="metric"><span>BEST START</span><strong>Pour Over</strong><small>4 curated recipes</small></div><div class="metric"><span>ESPRESSO TARGET</span><strong>18 → 36g</strong><small>1:2 brew ratio</small></div><div class="metric"><span>GUIDED AUDIO</span><strong>ON</strong><small>sound + haptics</small></div><div class="metric"><span>COFFEE BOOK</span><strong>${state.recipes.length}</strong><small>saved recipes</small></div></div></div>
<section class="section-head"><div><span class="eyebrow">RECIPE DECK</span><h2>Curated methods</h2></div><button class="text-btn" data-page="pour">View all →</button></section>
<div class="mini-grid">${R.slice(0,3).map((r,i)=>`<article class="mini-card"><div class="mini-num">0${i+1}</div><div><span>${esc(r.creator)}</span><h3>${esc(r.name)}</h3><p>${r.coffee_g}g · ${r.water_g}g · ${fmt(r.brew_seconds)}</p></div><button data-brew="${r.id}">Start</button></article>`).join('')}</div></section>`}

function pourPage(){return `<section class="page-head"><button class="back-btn" data-page="home">← Dashboard</button><div class="eyebrow">METHOD 01 / POUR OVER</div><h1>Dial in the pour.</h1><p>Choose a proven recipe. Pocket Barista becomes your brewing co-pilot.</p></section>
<section class="recipe-deck">${R.map((r,i)=>`<article class="recipe-panel"><div class="recipe-index">${String(i+1).padStart(2,'0')}</div><div class="recipe-main"><div class="recipe-line"><span class="recipe-badge">${esc(r.badge)}</span><span>${esc(r.creator)}</span></div><h2>${esc(r.name)}</h2><p>${esc(r.notes)}</p><div class="specs"><span><b>${r.coffee_g}g</b> coffee</span><span><b>${r.water_g}g</b> water</span><span><b>1:${r.ratio}</b> ratio</span><span><b>${r.temperature_c}°</b> water</span><span><b>${fmt(r.brew_seconds)}</b> target</span></div><div class="recipe-buttons"><button class="primary" data-brew="${r.id}">Brew guided</button><button class="ghost" data-use="${r.id}">Use recipe</button>${r.sourceUrl?`<a class="source-link" href="${r.sourceUrl}" target="_blank" rel="noreferrer">Source ↗</a>`:''}</div></div></article>`).join('')}</section>
<section class="section-head"><div><span class="eyebrow">CUSTOM BUILD</span><h2>Build your cup</h2></div><span class="pill" id="ratioPill">1:${ratio()?ratio().toFixed(1):'16.0'}</span></section>${calculator()}`}

function calculator(){return `<section class="panel calculator"><div class="grid two"><label>Coffee (g)<input id="coffee" type="number" min="1" step="0.1" value="20"></label><label>Water (g)<input id="water" type="number" min="1" value="320"></label></div><div class="ratio-bar"><span></span></div><div class="grid two"><label>Method<select id="method"><option>Pour Over</option><option>AeroPress</option><option>French Press</option><option>Espresso</option><option>Cold Brew</option></select></label><label>Grind<select id="grind"><option>Medium-fine</option><option>Fine</option><option>Medium</option><option>Medium-coarse</option><option>Coarse</option></select></label></div><div class="grid two"><label>Temperature °C<input id="temp" type="number" value="94"></label><label>Brew time sec<input id="brewTime" type="number" value="180"></label></div><label>Recipe name<input id="recipeName" placeholder="Sunday V60"></label><label>Tasting notes<textarea id="notes" rows="3" placeholder="Sweet, juicy, clean…"></textarea></label><div class="actions"><button class="primary" id="saveBtn">Save to coffee book</button><button class="secondary" id="resetBtn">Reset</button></div></section>`}

function espressoPage(){const s=state.shot;const remaining=Math.max(0,s.target-s.elapsed);return `<section class="page-head espresso-head"><button class="back-btn" data-page="home">← Dashboard</button><div class="eyebrow">METHOD 02 / ESPRESSO</div><h1>Pull the shot.</h1><p>Simple, tactile timing for dialing in espresso.</p></section><section class="shot-console"><div class="shot-top"><div><span class="eyebrow">SHOT TIMER</span><h2>${s.running?'EXTRACTING':'READY'}</h2></div><div class="live-ring ${s.running?'live':''}"><span></span></div></div><div class="shot-time">${s.elapsed.toFixed(1)}<small>s</small></div><div class="shot-track"><span style="width:${Math.min(100,s.elapsed/s.target*100)}%"></span></div><div class="shot-target"><span>NEXT TARGET</span><strong>${remaining.toFixed(1)}s</strong><span>target ${s.target}s</span></div><div class="shot-controls"><button class="primary shot-main" id="shotToggle">${s.running?'Stop shot':'Start shot'}</button><button class="secondary" id="shotReset">Reset</button></div></section><section class="dose-grid"><label class="panel dose-card"><span>DOSE</span><strong><input id="dose" type="number" step="0.1" value="${s.dose}"> <em>g</em></strong><small>ground coffee</small></label><label class="panel dose-card"><span>YIELD</span><strong><input id="yield" type="number" step="0.1" value="${s.yield}"> <em>g</em></strong><small>liquid espresso</small></label><div class="panel ratio-card"><span>BREW RATIO</span><strong>1:${(s.yield/s.dose).toFixed(2)}</strong><small>classic starting point</small></div></section><section class="shot-presets"><span class="eyebrow">TARGET WINDOW</span><div>${[25,28,30,32,35].map(x=>`<button class="${s.target===x?'selected':''}" data-shot-target="${x}">${x}s</button>`).join('')}</div></section><section class="panel dial-notes"><span class="eyebrow">DIAL-IN NOTES</span><div class="note-row"><span>FASTER</span><p>Grind finer if the shot runs too quickly.</p></div><div class="note-row"><span>SLOWER</span><p>Grind coarser if the shot runs too slowly.</p></div><div class="note-row"><span>RATIO</span><p>Start around 1:2, then adjust for taste.</p></div></section>`}

function recipeMarkup(){if(!state.user)return `<div class="empty panel"><div class="empty-icon">✦</div><h3>Your private coffee book</h3><p>Sign in to save recipes across devices.</p><button class="primary" id="emptyAuth">Sign in / create account</button></div>`;if(!state.recipes.length)return `<div class="empty panel"><h3>No saved recipes yet.</h3><p>Save a curated method or custom brew.</p></div>`;return state.recipes.map(r=>`<article class="recipe panel"><div><div class="recipe-title">${esc(r.name)}</div><div>${esc(r.method)} · ${r.coffee_g}g / ${r.water_g}g</div><div class="recipe-meta">1:${(+r.ratio||r.water_g/r.coffee_g).toFixed(1)} · ${esc(r.grind||'—')} · ${r.temperature_c||'—'}°C · ${fmt(r.brew_seconds||0)}</div></div><div class="recipe-actions"><button data-load="${r.id}">↺</button><button data-delete="${r.id}">×</button></div></article>`).join('')}

function bind(){
 document.querySelector('#menuBtn').onclick=openMenu;document.querySelector('#navMenu').onclick=openMenu;document.querySelector('#authBtn').onclick=openAuth;
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});
 document.querySelectorAll('[data-brew]').forEach(b=>b.onclick=()=>startGuide(b.dataset.brew));document.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{const r=R.find(x=>x.id===b.dataset.use);if(r){state.page='pour';render();setTimeout(()=>useBuilt(r),0)}});
 document.querySelector('#coffee')?.addEventListener('input',updateRatio);document.querySelector('#water')?.addEventListener('input',updateRatio);document.querySelector('#saveBtn')?.addEventListener('click',saveRecipe);document.querySelector('#resetBtn')?.addEventListener('click',resetForm);document.querySelector('#emptyAuth')?.addEventListener('click',openAuth);
 document.querySelector('#shotToggle')?.addEventListener('click',toggleShot);document.querySelector('#shotReset')?.addEventListener('click',resetShot);document.querySelector('#dose')?.addEventListener('input',e=>{state.shot.dose=+e.target.value||18;updateShotRatio()});document.querySelector('#yield')?.addEventListener('input',e=>{state.shot.yield=+e.target.value||36;updateShotRatio()});document.querySelectorAll('[data-shot-target]').forEach(b=>b.onclick=()=>{state.shot.target=+b.dataset.shotTarget;render()});
 document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>loadRecipe(b.dataset.load));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteRecipe(b.dataset.delete));
}
function openMenu(){document.querySelector('#modal').innerHTML=`<div class="menu-backdrop"><aside class="drawer"><div class="drawer-head"><div class="brand"><div class="brand-mark small"><span></span></div><div><div class="eyebrow">POCKET BARISTA</div><div class="brand-title">PB<span>01</span></div></div></div><button class="close" id="closeMenu">×</button></div><div class="drawer-label">METHODS</div><button class="drawer-item" data-menu-page="home"><b>01</b><span>Dashboard</span><i>→</i></button><button class="drawer-item" data-menu-page="pour"><b>02</b><span>Pour Over</span><i>→</i></button><button class="drawer-item" data-menu-page="espresso"><b>03</b><span>Espresso shot timer</span><i>→</i></button><div class="drawer-label">LIBRARY</div><button class="drawer-item" id="drawerSaved"><b>04</b><span>My coffee book</span><i>→</i></button><div class="drawer-foot"><span>PB / 01</span><small>Precision brewing utility</small></div></aside></div>`;document.querySelector('#closeMenu').onclick=closeMenu;document.querySelectorAll('[data-menu-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.menuPage;closeMenu();render()});document.querySelector('#drawerSaved').onclick=()=>{closeMenu();state.page='pour';render();setTimeout(()=>document.querySelector('#recipes')?.scrollIntoView({behavior:'smooth'}),50)}}
function closeMenu(){document.querySelector('#modal').innerHTML=''}
function updateRatio(){const r=ratio();const p=document.querySelector('#ratioPill');if(p)p.textContent=`1:${r?r.toFixed(1):'—'}`;const bar=document.querySelector('.ratio-bar span');if(bar)bar.style.width=`${Math.min(100,Math.max(8,r/25*100))}%`}
function resetForm(){for(const id of ['recipeName','notes'])document.querySelector('#'+id).value='';document.querySelector('#coffee').value=20;document.querySelector('#water').value=320;document.querySelector('#temp').value=94;document.querySelector('#brewTime').value=180;updateRatio()}
function useBuilt(r){for(const [id,v] of [['coffee',r.coffee_g],['water',r.water_g],['method',r.method],['grind',r.grind],['temp',r.temperature_c],['brewTime',r.brew_seconds],['recipeName',r.name],['notes',r.notes]])document.querySelector('#'+id).value=v;updateRatio();document.querySelector('#coffee')?.scrollIntoView({behavior:'smooth',block:'center'})}
function loadRecipe(id){const r=state.recipes.find(x=>x.id===id);if(!r)return;for(const [k,v] of [['coffee',r.coffee_g],['water',r.water_g],['method',r.method],['grind',r.grind||'Medium'],['temp',r.temperature_c||94],['brewTime',r.brew_seconds||180],['recipeName',r.name],['notes',r.notes||'']])document.querySelector('#'+k).value=v;updateRatio()}
async function loadRecipes(){if(!supabase||!state.user){state.recipes=[];return}const {data,error}=await supabase.from('recipes').select('*').order('created_at',{ascending:false});if(error)return toast(error.message);state.recipes=data||[];render()}
async function saveRecipe(){if(!supabase)return toast('Supabase is not configured.');if(!state.user)return openAuth();const c=+document.querySelector('#coffee').value,w=+document.querySelector('#water').value;if(!c||!w)return toast('Add coffee and water first.');const p={user_id:state.user.id,name:document.querySelector('#recipeName').value.trim()||'My brew',method:document.querySelector('#method').value,coffee_g:c,water_g:w,ratio:w/c,grind:document.querySelector('#grind').value,temperature_c:+document.querySelector('#temp').value,brew_seconds:+document.querySelector('#brewTime').value,notes:document.querySelector('#notes').value.trim(),rating:0};const {error}=await supabase.from('recipes').insert(p);if(error)return toast(error.message);toast('Recipe saved ✓');await loadRecipes()}
async function saveBuilt(id){if(!state.user)return openAuth();const r=R.find(x=>x.id===id);if(!r)return;const {error}=await supabase.from('recipes').insert({user_id:state.user.id,name:r.name,method:r.method,coffee_g:r.coffee_g,water_g:r.water_g,ratio:r.ratio,grind:r.grind,temperature_c:r.temperature_c,brew_seconds:r.brew_seconds,notes:`Inspired by ${r.creator}. ${r.notes}`,rating:0});if(error)return toast(error.message);toast('Added to your coffee book ✓');await loadRecipes()}
async function deleteRecipe(id){if(!supabase||!confirm('Delete this recipe?'))return;const {error}=await supabase.from('recipes').delete().eq('id',id);if(error)return toast(error.message);await loadRecipes()}
function startGuide(id){const r=R.find(x=>x.id===id);if(!r)return;stopGuide();state.guide={r,elapsed:0,step:0,running:false};renderGuide()}
function renderGuide(){const g=state.guide;if(!g)return;const r=g.r,s=r.steps[g.step],remain=Math.max(0,s[1]-g.elapsed),pct=Math.min(100,g.elapsed/r.brew_seconds*100);document.querySelector('#modal').innerHTML=`<div class="guide-backdrop"><div class="guide-shell"><header class="guide-top"><div><span class="eyebrow">GUIDED BREW · ${esc(r.creator)}</span><h2>${esc(r.name)}</h2></div><button class="close" id="closeGuide">×</button></header><div class="guide-progress"><span style="width:${pct}%"></span></div><div class="guide-clock"><div class="next-label">NEXT STEP IN</div><div class="countdown">${fmt(Math.ceil(remain))}</div><div class="total-line"><span>TOTAL BREW</span><strong>${fmt(Math.floor(g.elapsed))}</strong><em>/ ${fmt(r.brew_seconds)}</em></div></div><div class="guide-step"><div class="step-kicker">STEP ${g.step+1} / ${r.steps.length}</div><h3>${esc(s[0])}</h3><p>${esc(s[2])}</p><div class="step-target"><span>SCALE TARGET</span><strong>${esc(s[3])}</strong></div><div class="step-hint">${esc(s[4])}</div></div><div class="guide-controls"><button class="secondary" id="guideReset">Reset</button><button class="primary guide-main" id="guideToggle">${g.running?'Pause':'Start brew'}</button><button class="secondary" id="guideNext">Next</button></div><div class="guide-status"><span class="status-dot ${g.running?'live':''}"></span>${g.running?'RUNNING · sound + vibration enabled':'Ready when you are'}</div></div></div>`;document.querySelector('#closeGuide').onclick=stopGuide;document.querySelector('#guideReset').onclick=()=>{g.elapsed=0;g.step=0;g.running=false;renderGuide()};document.querySelector('#guideToggle').onclick=()=>{primeAudio();g.running=!g.running;renderGuide()};document.querySelector('#guideNext').onclick=()=>advanceGuide(true)}
function tickGuide(){const g=state.guide;if(!g||!g.running)return;g.elapsed+=.1;const s=g.r.steps[g.step];if(g.elapsed>=s[1])advanceGuide(false);else updateGuideClock()}
function updateGuideClock(){const g=state.guide;if(!g)return;const s=g.r.steps[g.step],cd=document.querySelector('.countdown'),tot=document.querySelector('.total-line strong'),bar=document.querySelector('.guide-progress span');if(cd)cd.textContent=fmt(Math.ceil(Math.max(0,s[1]-g.elapsed)));if(tot)tot.textContent=fmt(Math.floor(g.elapsed));if(bar)bar.style.width=`${Math.min(100,g.elapsed/g.r.brew_seconds*100)}%`}
function advanceGuide(manual){const g=state.guide;if(!g)return;const next=g.step+1;if(next>=g.r.steps.length){g.elapsed=g.r.brew_seconds;g.running=false;notify('Brew complete');renderGuide();return}g.step=next;if(manual)g.elapsed=Math.max(g.elapsed,g.r.steps[next][0]);notify(`Next: ${g.r.steps[next][0]}`);renderGuide()}
function stopGuide(){state.guide=null;document.querySelector('#modal').innerHTML=''}
let audioCtx=null;function primeAudio(){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume?.()}catch{}}function beep(){try{if(!audioCtx)primeAudio();const o=audioCtx.createOscillator(),v=audioCtx.createGain();o.frequency.value=740;o.type='sine';v.gain.setValueAtTime(.0001,audioCtx.currentTime);v.gain.exponentialRampToValueAtTime(.12,audioCtx.currentTime+.01);v.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.24);o.connect(v);v.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.25)}catch{}}function vibrate(){navigator.vibrate?.([80,50,120])}function notify(m){beep();vibrate();toast(m)}
function toggleShot(){primeAudio();if(state.shot.running){stopShot();return}state.shot.running=true;state.shot.interval=setInterval(()=>{state.shot.elapsed+=.1;if(state.shot.elapsed>=state.shot.target){beep();vibrate();toast('Target reached');state.shot.running=false;clearInterval(state.shot.interval);state.shot.interval=null}render();},100);render()}
function stopShot(){state.shot.running=false;clearInterval(state.shot.interval);state.shot.interval=null;render()}
function resetShot(){clearInterval(state.shot.interval);state.shot.running=false;state.shot.interval=null;state.shot.elapsed=0;render()}
function updateShotRatio(){const el=document.querySelector('.ratio-card strong');if(el)el.textContent=`1:${(state.shot.yield/state.shot.dose).toFixed(2)}`}
function openAuth(){if(state.user)return supabase?.auth.signOut();document.querySelector('#modal').innerHTML=`<div class="modal-backdrop"><div class="modal panel"><button class="close" id="closeModal">×</button><span class="eyebrow">YOUR COFFEE BOOK</span><h2>Make it yours.</h2><p>Save recipes and access them on any device.</p><label>Email<input id="email" type="email"></label><label>Password<input id="password" type="password" minlength="6"></label><div class="actions"><button class="primary" id="signIn">Sign in</button><button class="secondary" id="signUp">Create account</button></div></div></div>`;document.querySelector('#closeModal').onclick=closeMenu;document.querySelector('#signIn').onclick=()=>auth(false);document.querySelector('#signUp').onclick=()=>auth(true)}
async function auth(up){const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value;if(!supabase)return;const x=up?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(x.error)return toast(x.error.message);closeMenu();if(up&&!x.data.session)toast('Check your email to confirm your account.')}
function toast(m){const t=document.createElement('div');t.className='toast';t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),2600)}
async function init(){render();if(!supabase)return;const {data}=await supabase.auth.getSession();state.user=data.session?.user||null;render();await loadRecipes();supabase.auth.onAuthStateChange(async(_,s)=>{state.user=s?.user||null;render();await loadRecipes()})}
init();state.guideLoop=setInterval(tickGuide,100);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/Pocket_Barista/sw.js').catch(()=>{}));
