import './style.css';
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';
const supabase = SUPABASE_URL && SUPABASE_KEY ? createClient(SUPABASE_URL, SUPABASE_KEY) : null;

const BUILT_IN_RECIPES = [
  { id:'hoffmann-v60', name:'Ultimate V60', creator:'James Hoffmann', badge:'Classic', method:'Pour Over', coffee_g:30, water_g:500, ratio:16.7, grind:'Medium-fine', temperature_c:100, brew_seconds:210, notes:'60g bloom, first main pour to 300g at 0:45, second to 500g at 1:15. Gentle agitation, then draw down.', sourceUrl:'https://www.youtube.com/watch?v=AI4ynXzkSQo' },
  { id:'hedrick-easy', name:'Easy & Effective V60', creator:'Lance Hedrick', badge:'High clarity', method:'Pour Over', coffee_g:20, water_g:340, ratio:17, grind:'Medium-fine', temperature_c:99, brew_seconds:180, notes:'Four pours with controlled spins. 50g bloom, then 100g, 220g and 340g targets.', sourceUrl:'https://gota.cafe/en/recipes/v60-02/hedrick-ultimate-v60' },
  { id:'rao-v60', name:'Rao Spin V60', creator:'Scott Rao', badge:'Precision', method:'Pour Over', coffee_g:22, water_g:360, ratio:16.4, grind:'Medium-fine', temperature_c:95, brew_seconds:180, notes:'66g bloom with gentle agitation, one continuous main pour, then a gentle stir and finishing spin.', sourceUrl:'https://www.scottrao.com/blog/2017/12/5/the-ideal-v60-technique' },
  { id:'april-v60', name:'April Four-Pour', creator:'April Coffee Roasters', badge:'Bright & clean', method:'Pour Over', coffee_g:13, water_g:200, ratio:15.4, grind:'Medium-coarse', temperature_c:92, brew_seconds:150, notes:'Four equal 50g pours at 0:00, 0:30, 1:00 and 1:30. Finish around 2:30.', sourceUrl:'https://www.aprilcoffeeroasters.com/pages/coffee-inf-recipes' }
];

const state = { user:null, recipes:[], timer:180, timerRunning:false, timerId:null };
const app = document.querySelector('#app');
const esc = (value='') => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const ratio = () => { const c=Number(document.querySelector('#coffee')?.value||0); const w=Number(document.querySelector('#water')?.value||0); return c ? w/c : 0; };
const fmtTime = s => `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;

function render(){
  const signedIn = !!state.user;
  app.innerHTML = `
    <header class="topbar">
      <div class="brand"><div class="brand-mark"><span></span></div><div><span class="eyebrow">POCKET BARISTA</span><h1>Brew like you mean it.</h1></div></div>
      <button class="icon-btn" id="authBtn" aria-label="Account">${signedIn?'↪':'☕'}</button>
    </header>
    <main>
      <section class="hero">
        <div class="hero-copy"><div class="hero-kicker"><span class="pulse-dot"></span> YOUR DAILY BREW LAB</div><h2>Good coffee.<br><em>Dialled in.</em></h2><p>Recipes, ratios and a focused timer — wrapped in one calm little coffee lab.</p><div class="hero-actions"><button class="primary" id="heroBrew">Build a brew</button><button class="ghost" id="heroRecipes">Explore recipes</button></div></div>
        <div class="hero-orbit" aria-hidden="true"><div class="orbit-ring"></div><div class="cup"><div class="coffee-surface"></div><i></i><i></i><i></i></div><div class="bean bean-a">●</div><div class="bean bean-b">●</div><div class="bean bean-c">●</div></div>
      </section>
      <section class="stats-strip"><div><strong>4</strong><span>signature recipes</span></div><div><strong>1:17</strong><span>sweet spot ratio</span></div><div><strong>99°</strong><span>high-clarity brew</span></div></section>
      <section class="section-head"><div><p class="eyebrow">BREW CALCULATOR</p><h2>Build your cup</h2></div><span class="pill" id="ratioPill">1:${ratio()?ratio().toFixed(1):'16.0'}</span></section>
      <section class="card calculator">
        <div class="grid two"><label>Coffee (g)<input id="coffee" type="number" min="1" step="0.1" value="20"></label><label>Water (g)<input id="water" type="number" min="1" step="1" value="320"></label></div>
        <div class="ratio-bar"><span></span></div>
        <div class="grid two"><label>Method<select id="method"><option>Pour Over</option><option>AeroPress</option><option>French Press</option><option>Espresso</option><option>Cold Brew</option></select></label><label>Grind<select id="grind"><option>Medium-fine</option><option>Fine</option><option>Medium</option><option>Medium-coarse</option><option>Coarse</option></select></label></div>
        <div class="grid two"><label>Temperature (°C)<input id="temp" type="number" value="94"></label><label>Brew time (sec)<input id="brewTime" type="number" value="180"></label></div>
        <label>Recipe name<input id="recipeName" placeholder="e.g. Sunday V60"></label><label>Tasting notes<textarea id="notes" rows="3" placeholder="Sweet, juicy, clean…"></textarea></label>
        <div class="actions"><button class="primary" id="saveBtn">Save to my book</button><button class="secondary" id="resetBtn">Reset</button></div>
      </section>
      <section class="section-head"><div><p class="eyebrow">CURATED BREWS</p><h2>Recipes worth trying</h2></div></section>
      <section class="recipe-grid" id="featuredRecipes">${builtInMarkup()}</section>
      <section class="section-head"><div><p class="eyebrow">BREW TIMER</p><h2>Stay in the moment.</h2></div></section>
      <section class="card timer-card"><div class="timer-ring"><div class="timer" id="timer">${fmtTime(state.timer)}</div><span>${state.timerRunning?'BREWING':'READY'}</span></div><div class="timer-actions"><button class="primary" id="timerToggle">${state.timerRunning?'Pause':'Start timer'}</button><button class="secondary" id="timerReset">Reset</button></div></section>
      <section class="section-head"><div><p class="eyebrow">MY RECIPES</p><h2>Saved brews</h2></div></section><section id="recipes" class="recipe-list">${recipeMarkup()}</section>
      <footer><span class="brand-dot"></span> Pocket Barista <span>•</span> brew with intention</footer>
    </main>
    <nav class="bottom-nav"><a class="active" href="#top">☕<span>Brew</span></a><a href="#recipes">▤<span>Recipes</span></a><button id="navTimer">◷<span>Timer</span></button></nav><div id="modal"></div>`;
  bind();
}

function builtInMarkup(){return BUILT_IN_RECIPES.map(r=>`<article class="feature-card"><div class="feature-top"><span class="recipe-badge">${esc(r.badge)}</span><span class="creator">${esc(r.creator)}</span></div><div class="mini-cup"><span></span></div><h3>${esc(r.name)}</h3><p class="muted">${esc(r.method)} · ${r.coffee_g}g / ${r.water_g}g</p><div class="feature-metrics"><span><b>1:${r.ratio}</b> ratio</span><span><b>${r.temperature_c}°</b> water</span><span><b>${fmtTime(r.brew_seconds)}</b> target</span></div><div class="feature-actions"><button class="secondary" data-brew="${r.id}">Brew this</button><button class="text-btn" data-save-built="${r.id}">${state.user?'Save':'Sign in to save'} ↗</button></div></article>`).join('');}
function recipeMarkup(){if(!state.user)return `<div class="empty card"><div class="empty-icon">✦</div><h3>Your private coffee book</h3><p class="muted">Sign in to save your dialled-in recipes and carry them between devices.</p><button class="primary" id="emptyAuth">Sign in / create account</button></div>`;if(!state.recipes.length)return `<div class="empty card"><div class="empty-icon">☕</div><h3>No saved recipes yet.</h3><p class="muted">Start from a curated recipe above or build one from scratch.</p></div>`;return state.recipes.map(r=>`<article class="recipe card"><div><div class="recipe-title">${esc(r.name)}</div><div class="muted">${esc(r.method)} · ${r.coffee_g}g coffee · ${r.water_g}g water</div><div class="recipe-meta">1:${Number(r.ratio||r.water_g/r.coffee_g).toFixed(1)} · ${esc(r.grind||'—')} · ${r.temperature_c||'—'}°C · ${fmtTime(r.brew_seconds||0)}</div></div><div class="recipe-actions"><button data-load="${r.id}" title="Load">↺</button><button data-delete="${r.id}" title="Delete">×</button></div></article>`).join('');}
function bind(){document.querySelector('#coffee').addEventListener('input',updateRatio);document.querySelector('#water').addEventListener('input',updateRatio);document.querySelector('#saveBtn').addEventListener('click',saveRecipe);document.querySelector('#resetBtn').addEventListener('click',resetForm);document.querySelector('#timerToggle').addEventListener('click',toggleTimer);document.querySelector('#timerReset').addEventListener('click',resetTimer);document.querySelector('#navTimer').addEventListener('click',()=>document.querySelector('#timer')?.scrollIntoView({behavior:'smooth'}));document.querySelector('#authBtn').addEventListener('click',openAuth);document.querySelector('#emptyAuth')?.addEventListener('click',openAuth);document.querySelector('#heroBrew').addEventListener('click',()=>document.querySelector('#coffee')?.scrollIntoView({behavior:'smooth',block:'center'}));document.querySelector('#heroRecipes').addEventListener('click',()=>document.querySelector('#featuredRecipes')?.scrollIntoView({behavior:'smooth',block:'start'}));document.querySelectorAll('[data-brew]').forEach(b=>b.addEventListener('click',()=>useBuiltIn(b.dataset.brew)));document.querySelectorAll('[data-save-built]').forEach(b=>b.addEventListener('click',()=>saveBuiltIn(b.dataset.saveBuilt)));document.querySelectorAll('[data-load]').forEach(b=>b.addEventListener('click',()=>loadRecipe(b.dataset.load)));document.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>deleteRecipe(b.dataset.delete)));}
function updateRatio(){const r=ratio();document.querySelector('#ratioPill').textContent=`1:${r?r.toFixed(1):'—'}`;const bar=document.querySelector('.ratio-bar span');if(bar)bar.style.width=`${Math.min(100,Math.max(8,r/25*100))}%`;}
function resetForm(){document.querySelector('#recipeName').value='';document.querySelector('#notes').value='';document.querySelector('#coffee').value=20;document.querySelector('#water').value=320;document.querySelector('#temp').value=94;document.querySelector('#brewTime').value=180;updateRatio();}
async function loadRecipes(){if(!supabase||!state.user){state.recipes=[];render();return;}const {data,error}=await supabase.from('recipes').select('*').order('created_at',{ascending:false});if(error)return toast(error.message);state.recipes=data||[];render();}
function useBuiltIn(id){const r=BUILT_IN_RECIPES.find(x=>x.id===id);if(!r)return;document.querySelector('#coffee').value=r.coffee_g;document.querySelector('#water').value=r.water_g;document.querySelector('#method').value=r.method;document.querySelector('#grind').value=r.grind;document.querySelector('#temp').value=r.temperature_c;document.querySelector('#brewTime').value=r.brew_seconds;document.querySelector('#recipeName').value=r.name;document.querySelector('#notes').value=r.notes;updateRatio();document.querySelector('#coffee').scrollIntoView({behavior:'smooth',block:'center'});toast(`${r.creator} recipe loaded`);}
async function saveBuiltIn(id){if(!state.user)return openAuth();const r=BUILT_IN_RECIPES.find(x=>x.id===id);if(!r)return;const {error}=await supabase.from('recipes').insert({user_id:state.user.id,name:r.name,method:r.method,coffee_g:r.coffee_g,water_g:r.water_g,ratio:r.ratio,grind:r.grind,temperature_c:r.temperature_c,brew_seconds:r.brew_seconds,notes:`Inspired by ${r.creator}. ${r.notes}`,rating:0});if(error)return toast(error.message);toast('Added to your coffee book ✓');await loadRecipes();}
async function saveRecipe(){if(!supabase)return toast('Supabase is not configured.');if(!state.user)return openAuth();const coffee=Number(document.querySelector('#coffee').value),water=Number(document.querySelector('#water').value);if(!coffee||!water)return toast('Add coffee and water amounts first.');const payload={user_id:state.user.id,name:document.querySelector('#recipeName').value.trim()||`${document.querySelector('#method').value} recipe`,method:document.querySelector('#method').value,coffee_g:coffee,water_g:water,ratio:water/coffee,grind:document.querySelector('#grind').value,temperature_c:Number(document.querySelector('#temp').value),brew_seconds:Number(document.querySelector('#brewTime').value),notes:document.querySelector('#notes').value.trim(),rating:0};const {error}=await supabase.from('recipes').insert(payload);if(error)return toast(error.message);toast('Recipe saved ✓');await loadRecipes();}
function loadRecipe(id){const r=state.recipes.find(x=>x.id===id);if(!r)return;document.querySelector('#coffee').value=r.coffee_g;document.querySelector('#water').value=r.water_g;document.querySelector('#method').value=r.method;document.querySelector('#grind').value=r.grind||'Medium';document.querySelector('#temp').value=r.temperature_c||94;document.querySelector('#brewTime').value=r.brew_seconds||180;document.querySelector('#recipeName').value=r.name;document.querySelector('#notes').value=r.notes||'';updateRatio();window.scrollTo({top:0,behavior:'smooth'});}
async function deleteRecipe(id){if(!supabase||!confirm('Delete this recipe?'))return;const {error}=await supabase.from('recipes').delete().eq('id',id);if(error)return toast(error.message);await loadRecipes();}
function openAuth(){if(state.user)return supabase.signOut();document.querySelector('#modal').innerHTML=`<div class="modal-backdrop"><div class="modal card"><button class="close" id="closeModal">×</button><p class="eyebrow">YOUR COFFEE BOOK</p><h2>Make it yours.</h2><p class="muted">Save recipes and access them on any device.</p><label>Email<input id="email" type="email" autocomplete="email"></label><label>Password<input id="password" type="password" autocomplete="current-password" minlength="6"></label><div class="actions"><button class="primary" id="signIn">Sign in</button><button class="secondary" id="signUp">Create account</button></div><p class="fine">No payment details. Your recipes belong to your account.</p></div></div>`;document.querySelector('#closeModal').onclick=closeModal;document.querySelector('#signIn').onclick=()=>auth(false);document.querySelector('#signUp').onclick=()=>auth(true);}
async function auth(signUp){if(!supabase)return toast('Supabase is not configured.');const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value;const result=signUp?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(result.error)return toast(result.error.message);closeModal();if(signUp&&!result.data.session)toast('Check your email to confirm your account.');}
function closeModal(){document.querySelector('#modal').innerHTML='';}
function toggleTimer(){state.timerRunning=!state.timerRunning;clearInterval(state.timerId);if(state.timerRunning)state.timerId=setInterval(()=>{if(state.timer<=0){state.timerRunning=false;clearInterval(state.timerId);toast('Brew complete ☕');return;}state.timer--;renderTimerOnly();},1000);renderTimerOnly();}
function resetTimer(){clearInterval(state.timerId);state.timerRunning=false;state.timer=180;renderTimerOnly();}
function renderTimerOnly(){const el=document.querySelector('#timer');if(el)el.textContent=fmtTime(state.timer);const b=document.querySelector('#timerToggle');if(b)b.textContent=state.timerRunning?'Pause':'Start timer';const status=document.querySelector('.timer-ring span');if(status)status.textContent=state.timerRunning?'BREWING':'READY';}
function toast(message){const t=document.createElement('div');t.className='toast';t.textContent=message;document.body.appendChild(t);setTimeout(()=>t.remove(),3200);}
async function init(){render();if(!supabase)return;const {data}=await supabase.auth.getSession();state.user=data.session?.user||null;await loadRecipes();supabase.auth.onAuthStateChange(async(_event,session)=>{state.user=session?.user||null;await loadRecipes();});}
init();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/Pocket_Barista/sw.js').catch(()=>{}));
