import './style.css';
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';
const supabase = SUPABASE_URL && SUPABASE_KEY ? createClient(SUPABASE_URL, SUPABASE_KEY) : null;

const R = [
 {id:'hoffmann-v60',name:'Ultimate V60',creator:'James Hoffmann',badge:'Signature',method:'Pour Over',coffee_g:30,water_g:500,ratio:16.7,grind:'Medium-fine',temperature_c:97,brew_seconds:210,notes:'60g bloom, two main pours, final bed-settle.',sourceUrl:'https://www.hario-usa.com/blogs/recipes-and-more-from-friends/james-hoffmann-uitimate-v60',steps:[['Bloom',45,'Pour to 60g and swirl gently.','60g','Wet every ground.'],['First pour',75,'Pour steadily to 300g.','300g','Keep the flow smooth.'],['Finish water',105,'Pour more gently to 500g.','500g','Keep the bed topped up.'],['Set the bed',120,'Stir once each way, then gently swirl.','—','Flatten the bed.'],['Drawdown',210,'Leave it to drain until the bed is flat.','—','Aim for 3:30 total.']]},
 {id:'hedrick-easy',name:'Easy & Effective V60',creator:'Lance Hedrick',badge:'High clarity',method:'Pour Over',coffee_g:20,water_g:340,ratio:17,grind:'Medium-fine',temperature_c:100,brew_seconds:210,notes:'Four pours with controlled spins.',sourceUrl:'https://www.youtube.com/watch?v=Ji4lZTtRAoo',steps:[['Bloom',30,'Pour 50g and spin.','50g','Boiling water is intentional.'],['Second pour',60,'Pour to 100g and spin.','100g','Keep the motion controlled.'],['Third pour',90,'Pour to 220g and spin.','220g','Aim just behind centre.'],['Final pour',120,'Pour to 340g and spin.','340g','One final controlled spin.'],['Drawdown',210,'Let the brew drain completely.','—','Typical finish 2:30–3:30.']]},
 {id:'rao-v60',name:'Rao Spin V60',creator:'Scott Rao',badge:'Precision',method:'Pour Over',coffee_g:22,water_g:360,ratio:16.4,grind:'Medium-fine',temperature_c:95,brew_seconds:180,notes:'Bloom agitation, one continuous main pour and a finishing spin.',sourceUrl:'https://www.scottrao.com/blog/2017/12/5/the-ideal-v60-technique',steps:[['Bloom',45,'Pour 66g and gently agitate.','66g','Even saturation is the goal.'],['Main pour',80,'Pour continuously to 360g.','360g','Keep a consistent stream.'],['Release walls',110,'Gently stir grounds away from the walls.','360g','Keep agitation gentle.'],['Rao spin + drawdown',180,'Gently spin to level the bed, then drain.','—','Finish around 3:00.']]},
 {id:'april-v60',name:'April Four-Pour',creator:'April Coffee Roasters',badge:'Bright & clean',method:'Pour Over',coffee_g:13,water_g:200,ratio:15.4,grind:'Medium-coarse',temperature_c:92,brew_seconds:150,notes:'Four equal pours at 30-second intervals.',sourceUrl:'https://www.aprilcoffeeroasters.com/pages/coffee-inf-recipes',steps:[['Pour one',30,'Pour to 50g.','50g','Establish an even bed.'],['Pour two',60,'Pour to 100g.','100g','Repeat the same motion.'],['Pour three',90,'Pour to 150g.','150g','Keep the flow consistent.'],['Pour four',120,'Pour to 200g.','200g','Finish without flooding.'],['Drawdown',150,'Let the coffee drain.','—','Aim for 2:30 total.']]}
];

const state={user:null,recipes:[],page:'home',timer:180,timerRunning:false,timerId:null,guide:null,guideLoop:null,shot:{elapsed:0,running:false,target:30,interval:null,dose:18,yield:36,targetNotified:false}};
const app=document.querySelector('#app');
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const fmt=s=>{const n=Number(s);const safe=Number.isFinite(n)?Math.max(0,n):0;return `${String(Math.floor(safe/60)).padStart(2,'0')}:${String(Math.floor(safe%60)).padStart(2,'0')}`};
const ratio=()=>{const c=+document.querySelector('#coffee')?.value||0,w=+document.querySelector('#water')?.value||0;return c?w/c:0};
let wakeLock=null;

function render(){
 app.innerHTML=`<div class="app-shell">
 <header class="topbar"><button class="menu-btn" id="menuBtn" aria-label="Open menu"><span></span><span></span></button><div class="brand"><div class="brand-mark"><span></span></div><div><div class="eyebrow">A MINOR INCONVENIENCE</div><div class="brand-title">POCKET BARISTA</div></div></div><button class="profile-btn" id="authBtn">${state.user?'●':'○'}</button></header>
 <main>
  ${state.page==='home'?homePage():state.page==='pour'?pourPage():espressoPage()}
 </main>
 <nav class="bottom-nav"><button class="${state.page==='home'?'active':''}" data-page="home"><b>⌂</b><span>Dashboard</span></button><button class="${state.page==='pour'?'active':''}" data-page="pour"><b>◒</b><span>Pour Over</span></button><button class="${state.page==='espresso'?'active':''}" data-page="espresso"><b>◉</b><span>Espresso</span></button><button id="navMenu"><b>≡</b><span>Menu</span></button></nav>
 <div id="modal"></div></div>`;
 bind();
}

function homePage(){return `<section class="dashboard-head"><div><h1>Good coffee.<br><em>Precisely made.</em></h1></div><div class="status-chip"><i></i> SYSTEM READY</div></section>
<section class="command-grid">
 <button class="command-card hero-command" data-page="pour"><div class="command-icon pour-icon">◒</div><div class="command-copy"><h2>Pour Over</h2></div><b>→</b></button>
 <button class="command-card" data-page="espresso"><div class="command-icon">◉</div><div class="command-copy"><h2>Espresso</h2></div><b>→</b></button>
</section>`}

function pourPage(){return `<section class="page-head"><button class="back-btn" data-page="home">← Dashboard</button><div class="eyebrow">METHOD 01 / POUR OVER</div><h1>Dial in the pour.</h1><p>Choose a proven recipe. Pocket Barista becomes your brewing co-pilot.</p></section>
<section class="recipe-deck">${R.map((r,i)=>`<article class="recipe-panel" data-recipe-card="${r.id}"><div class="recipe-index">${String(i+1).padStart(2,'0')}</div><div class="recipe-main"><div class="recipe-line"><span class="recipe-badge">${esc(r.badge)}</span><span>${esc(r.creator)}</span></div><h2>${esc(r.name)}</h2><p>${esc(r.notes)}</p><div class="specs"><span><b data-scale-coffee="${r.id}">${r.coffee_g}g</b> coffee</span><span><b data-scale-water="${r.id}">${r.water_g}g</b> water</span><span><b>1:${r.ratio}</b> ratio</span><span><b>${r.temperature_c}°</b> water</span><span><b>${fmt(r.brew_seconds)}</b> target</span></div><div class="recipe-scale"><div class="recipe-scale-head"><span>BREW SIZE</span><strong data-scale-value="${r.id}">1.00×</strong></div><input class="recipe-scale-slider" data-recipe-scale="${r.id}" type="range" min="0.50" max="1.50" step="0.05" value="1" aria-label="Adjust coffee and water volume"></div><div class="recipe-buttons"><button class="primary" data-brew="${r.id}">Brew</button><button class="ghost" data-use="${r.id}">Use recipe</button>${r.sourceUrl?`<a class="source-link" href="${r.sourceUrl}" target="_blank" rel="noreferrer">Source ↗</a>`:''}</div></div></article>`).join('')}</section>
<section class="section-head"><div><span class="eyebrow">CUSTOM BUILD</span><h2>Build your cup</h2></div><span class="pill" id="ratioPill">1:${ratio()?ratio().toFixed(1):'16.0'}</span></section>${calculator()}`}

function calculator(){return `<section class="panel calculator"><div class="grid two"><label>Coffee (g)<input id="coffee" type="number" min="1" step="0.1" value="20"></label><label>Water (g)<input id="water" type="number" min="1" value="320"></label></div><div class="ratio-bar"><span></span></div><div class="grid two"><label>Method<select id="method"><option>Pour Over</option><option>AeroPress</option><option>French Press</option><option>Espresso</option><option>Cold Brew</option></select></label><label>Grind<select id="grind"><option>Medium-fine</option><option>Fine</option><option>Medium</option><option>Medium-coarse</option><option>Coarse</option></select></label></div><div class="grid two"><label>Temperature °C<input id="temp" type="number" value="94"></label><label>Brew time sec<input id="brewTime" type="number" value="180"></label></div><label>Recipe name<input id="recipeName" placeholder="Sunday V60"></label><label>Tasting notes<textarea id="notes" rows="3" placeholder="Sweet, juicy, clean…"></textarea></label><div class="actions"><button class="primary" id="saveBtn">Save to coffee book</button><button class="secondary" id="resetBtn">Reset</button></div></section>`}

function espressoPage(){const s=state.shot;const targetPct=s.target>0?Math.min(100,s.elapsed/s.target*100):0;return `<section class="espresso-minimal"><button class="back-btn" data-page="home">← Dashboard</button><section class="shot-console"><div class="shot-top"><div><span class="eyebrow">SHOT TIMER</span><h2>${s.running?'EXTRACTING':'READY'}</h2></div><div class="live-ring ${s.running?'live':''}"><span></span></div></div><div class="shot-time">${Number.isFinite(s.elapsed)?s.elapsed.toFixed(1):'0.0'}<small>s</small></div><div class="shot-track"><span style="width:${targetPct}%"></span></div><div class="shot-target"><span>TARGET</span><strong>${s.target}s</strong></div><div class="shot-controls"><button class="primary shot-main" id="shotToggle">${s.running?'Stop shot':'Start shot'}</button><button class="secondary" id="shotReset">Reset</button></div></section><section class="panel dial-notes"><span class="eyebrow">DIAL-IN NOTES</span><div class="note-row"><span>FASTER</span><p>Grind finer if the shot runs too quickly.</p></div><div class="note-row"><span>SLOWER</span><p>Grind coarser if the shot runs too slowly.</p></div><div class="note-row"><span>RATIO</span><p>Start around 1:2, then adjust for taste.</p></div></section></section>`}

function recipeMarkup(){if(!state.user)return `<div class="empty panel"><div class="empty-icon">✦</div><h3>Your private coffee book</h3><p>Sign in to save recipes across devices.</p><button class="primary" id="emptyAuth">Sign in / create account</button></div>`;if(!state.recipes.length)return `<div class="empty panel"><h3>No saved recipes yet.</h3><p>Save a curated method or custom brew.</p></div>`;return state.recipes.map(r=>`<article class="recipe panel"><div><div class="recipe-title">${esc(r.name)}</div><div>${esc(r.method)} · ${r.coffee_g}g / ${r.water_g}g</div><div class="recipe-meta">1:${(+r.ratio||r.water_g/r.coffee_g).toFixed(1)} · ${esc(r.grind||'—')} · ${r.temperature_c||'—'}°C · ${fmt(r.brew_seconds||0)}</div></div><div class="recipe-actions"><button data-load="${r.id}">↺</button><button data-delete="${r.id}">×</button></div></article>`).join('')}

function bind(){
 document.querySelector('#menuBtn').onclick=openMenu;document.querySelector('#navMenu').onclick=openMenu;document.querySelector('#authBtn').onclick=openAuth;
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{if(state.page!==b.dataset.page)releaseWakeLock();state.page=b.dataset.page;render()});
 document.querySelectorAll('[data-brew]').forEach(b=>b.onclick=()=>{const card=b.closest('[data-recipe-card]');const scale=+(card?.querySelector('[data-recipe-scale]')?.value||1);startGuide(b.dataset.brew,scale)});
 document.querySelectorAll('[data-recipe-scale]').forEach(sl=>sl.addEventListener('input',()=>updateRecipeScale(sl.dataset.recipeScale,sl.value)));
 document.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{const r=R.find(x=>x.id===b.dataset.use);if(r){state.page='pour';render();setTimeout(()=>useBuilt(r),0)}});
 document.querySelector('#coffee')?.addEventListener('input',updateRatio);document.querySelector('#water')?.addEventListener('input',updateRatio);document.querySelector('#saveBtn')?.addEventListener('click',saveRecipe);document.querySelector('#resetBtn')?.addEventListener('click',resetForm);document.querySelector('#emptyAuth')?.addEventListener('click',openAuth);
 document.querySelector('#shotToggle')?.addEventListener('click',toggleShot);document.querySelector('#shotReset')?.addEventListener('click',resetShot);
 document.querySelectorAll('[data-shot-target]').forEach(b=>b.onclick=()=>{state.shot.target=+b.dataset.shotTarget;render()});
 document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>loadRecipe(b.dataset.load));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteRecipe(b.dataset.delete));
}
function openMenu(){document.querySelector('#modal').innerHTML=`<div class="menu-backdrop"><aside class="drawer"><div class="drawer-head"><div class="brand"><div class="brand-mark small"><span></span></div><div><div class="eyebrow">A MINOR INCONVENIENCE</div><div class="brand-title">POCKET BARISTA</div></div></div><button class="close" id="closeMenu">×</button></div><div class="drawer-label">METHODS</div><button class="drawer-item" data-menu-page="home"><b>01</b><span>Dashboard</span><i>→</i></button><button class="drawer-item" data-menu-page="pour"><b>02</b><span>Pour Over</span><i>→</i></button><button class="drawer-item" data-menu-page="espresso"><b>03</b><span>Espresso shot timer</span><i>→</i></button><div class="drawer-label">LIBRARY</div><button class="drawer-item" id="drawerSaved"><b>04</b><span>My coffee book</span><i>→</i></button><div class="drawer-foot"><span>PB / 01</span><small>Precision brewing utility</small></div></aside></div>`;document.querySelector('#closeMenu').onclick=closeMenu;document.querySelectorAll('[data-menu-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.menuPage;closeMenu();render()});document.querySelector('#drawerSaved').onclick=()=>{closeMenu();state.page='pour';render();setTimeout(()=>document.querySelector('#recipes')?.scrollIntoView({behavior:'smooth'}),50)}}
function closeMenu(){document.querySelector('#modal').innerHTML=''}
function updateRatio(){const r=ratio();const p=document.querySelector('#ratioPill');if(p)p.textContent=`1:${r?r.toFixed(1):'—'}`;const bar=document.querySelector('.ratio-bar span');if(bar)bar.style.width=`${Math.min(100,Math.max(8,r/25*100))}%`}
function resetForm(){for(const id of ['recipeName','notes'])document.querySelector('#'+id).value='';document.querySelector('#coffee').value=20;document.querySelector('#water').value=320;document.querySelector('#temp').value=94;document.querySelector('#brewTime').value=180;updateRatio()}
function useBuilt(r){for(const [id,v] of [['coffee',r.coffee_g],['water',r.water_g],['method',r.method],['grind',r.grind],['temp',r.temperature_c],['brewTime',r.brew_seconds],['recipeName',r.name],['notes',r.notes]])document.querySelector('#'+id).value=v;updateRatio();document.querySelector('#coffee')?.scrollIntoView({behavior:'smooth',block:'center'})}
function updateRecipeScale(id,value){const r=R.find(x=>x.id===id);if(!r)return;const scale=Number(value);const coffee=roundBrew(r.coffee_g*scale);const water=roundBrew(r.water_g*scale);const v=document.querySelector(`[data-scale-value="${id}"]`),c=document.querySelector(`[data-scale-coffee="${id}"]`),w=document.querySelector(`[data-scale-water="${id}"]`);if(v)v.textContent=`${scale.toFixed(2)}×`;if(c)c.textContent=`${coffee}g`;if(w)w.textContent=`${water}g`}
function roundBrew(n){return Math.round(n*10)/10}
function scaledRecipe(base,scale=1){const factor=Number.isFinite(+scale)&&+scale>0?+scale:1;const scaleText=s=>String(s??'').replace(/(\d+(?:\.\d+)?)g\b/g,(_,n)=>`${roundBrew(+n*factor)}g`);return {...base,coffee_g:roundBrew(base.coffee_g*factor),water_g:roundBrew(base.water_g*factor),steps:base.steps.map(([name,time,desc,target,hint])=>[name,time,scaleText(desc),scaleText(target),scaleText(hint)])}}
function loadRecipe(id){const r=state.recipes.find(x=>x.id===id);if(!r)return;for(const [k,v] of [['coffee',r.coffee_g],['water',r.water_g],['method',r.method],['grind',r.grind||'Medium'],['temp',r.temperature_c||94],['brewTime',r.brew_seconds||180],['recipeName',r.name],['notes',r.notes||'']])document.querySelector('#'+k).value=v;updateRatio()}
async function loadRecipes(){if(!supabase||!state.user){state.recipes=[];return}const {data,error}=await supabase.from('recipes').select('*').order('created_at',{ascending:false});if(error)return toast(error.message);state.recipes=data||[];render()}
async function saveRecipe(){if(!supabase)return toast('Supabase is not configured.');if(!state.user)return openAuth();const c=+document.querySelector('#coffee').value,w=+document.querySelector('#water').value;if(!c||!w)return toast('Add coffee and water first.');const p={user_id:state.user.id,name:document.querySelector('#recipeName').value.trim()||'My brew',method:document.querySelector('#method').value,coffee_g:c,water_g:w,ratio:w/c,grind:document.querySelector('#grind').value,temperature_c:+document.querySelector('#temp').value,brew_seconds:+document.querySelector('#brewTime').value,notes:document.querySelector('#notes').value.trim(),rating:0};const {error}=await supabase.from('recipes').insert(p);if(error)return toast(error.message);toast('Recipe saved ✓');await loadRecipes()}
async function saveBuilt(id){if(!state.user)return openAuth();const r=R.find(x=>x.id===id);if(!r)return;const {error}=await supabase.from('recipes').insert({user_id:state.user.id,name:r.name,method:r.method,coffee_g:r.coffee_g,water_g:r.water_g,ratio:r.ratio,grind:r.grind,temperature_c:r.temperature_c,brew_seconds:r.brew_seconds,notes:`Inspired by ${r.creator}. ${r.notes}`,rating:0});if(error)return toast(error.message);toast('Added to your coffee book ✓');await loadRecipes()}
async function deleteRecipe(id){if(!supabase||!confirm('Delete this recipe?'))return;const {error}=await supabase.from('recipes').delete().eq('id',id);if(error)return toast(error.message);await loadRecipes()}
function startGuide(id,scale=1){const base=R.find(x=>x.id===id);if(!base)return;stopGuide();state.guide={r:scaledRecipe(base,scale),elapsed:0,step:0,running:false};renderGuide()}
function renderGuide(){const g=state.guide;if(!g)return;const r=g.r,s=r.steps[g.step]||r.steps[r.steps.length-1];const end=Number(s?.[1])||0;const elapsed=Number.isFinite(g.elapsed)?g.elapsed:0;g.elapsed=elapsed;const remain=Math.max(0,end-elapsed),pct=r.brew_seconds?Math.min(100,elapsed/r.brew_seconds*100):0;document.querySelector('#modal').innerHTML=`<div class="guide-backdrop"><div class="guide-shell"><header class="guide-top"><div><span class="eyebrow">GUIDED BREW · ${esc(r.creator)}</span><h2>${esc(r.name)}</h2><small class="guide-dose">${r.coffee_g}g coffee · ${r.water_g}g water · 1:${(r.water_g/r.coffee_g).toFixed(1)}</small></div><button class="close" id="closeGuide">×</button></header><div class="guide-progress"><span style="width:${pct}%"></span></div><div class="guide-clock"><div class="next-label">NEXT STEP IN</div><div class="countdown">${fmt(Math.ceil(remain))}</div><div class="total-line"><span>TOTAL BREW</span><strong>${fmt(Math.floor(elapsed))}</strong><em>/ ${fmt(r.brew_seconds)}</em></div></div><div class="guide-step"><div class="step-kicker">STEP ${g.step+1} / ${r.steps.length}</div><h3>${esc(s[0])}</h3><p>${esc(s[2])}</p><div class="step-target"><span>SCALE TARGET</span><strong>${esc(s[3])}</strong></div><div class="step-hint">${esc(s[4])}</div></div><div class="guide-controls"><button class="secondary" id="guideReset">Reset</button><button class="primary guide-main" id="guideToggle">${g.running?'Pause':'Start brew'}</button><button class="secondary" id="guideNext">Next</button></div><div class="guide-status"><span class="status-dot ${g.running?'live':''}"></span>${g.running?'RUNNING · sound + vibration enabled':'Ready when you are'}</div></div></div>`;document.querySelector('#closeGuide').onclick=stopGuide;document.querySelector('#guideReset').onclick=()=>{releaseWakeLock();g.elapsed=0;g.step=0;g.running=false;renderGuide()};document.querySelector('#guideToggle').onclick=()=>{primeAudio();g.running=!g.running;if(g.running)requestWakeLock();else releaseWakeLock();renderGuide()};document.querySelector('#guideNext').onclick=()=>advanceGuide(true)}
function tickGuide(){const g=state.guide;if(!g||!g.running)return;g.elapsed=Number.isFinite(g.elapsed)?g.elapsed+0.1:0.1;const s=g.r.steps[g.step];const end=Number(s?.[1])||0;if(g.elapsed>=end)advanceGuide(false);else updateGuideClock()}
function updateGuideClock(){const g=state.guide;if(!g)return;const s=g.r.steps[g.step];const end=Number(s?.[1])||0,cd=document.querySelector('.countdown'),tot=document.querySelector('.total-line strong'),bar=document.querySelector('.guide-progress span');if(cd)cd.textContent=fmt(Math.ceil(Math.max(0,end-g.elapsed)));if(tot)tot.textContent=fmt(Math.floor(g.elapsed));if(bar)bar.style.width=`${g.r.brew_seconds?Math.min(100,g.elapsed/g.r.brew_seconds*100):0}%`}
function advanceGuide(manual){const g=state.guide;if(!g)return;const next=g.step+1;if(next>=g.r.steps.length){g.elapsed=Number(g.r.brew_seconds)||g.elapsed;g.running=false;releaseWakeLock();notify('Brew complete');renderGuide();return}g.step=next;if(manual){const priorEnd=Number(g.r.steps[g.step]?.[1])||0;g.elapsed=Math.max(g.elapsed,priorEnd)}notify(`Next: ${g.r.steps[next][0]}`);renderGuide()}
function stopGuide(){if(state.guide?.running)releaseWakeLock();state.guide=null;document.querySelector('#modal').innerHTML=''}
let audioCtx=null;function primeAudio(){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume?.()}catch{}}function beep(){try{if(!audioCtx)primeAudio();if(!audioCtx)return;const o=audioCtx.createOscillator(),v=audioCtx.createGain();o.frequency.value=740;o.type='sine';v.gain.setValueAtTime(.0001,audioCtx.currentTime);v.gain.exponentialRampToValueAtTime(.12,audioCtx.currentTime+.01);v.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.24);o.connect(v);v.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.25)}catch{}}function vibrate(){navigator.vibrate?.([80,50,120])}function notify(m){beep();vibrate();toast(m)}
async function requestWakeLock(){if(!('wakeLock'in navigator)||document.visibilityState!=='visible')return;if(wakeLock&&!wakeLock.released)return;try{wakeLock=await navigator.wakeLock.request('screen');wakeLock.addEventListener('release',()=>{wakeLock=null})}catch{wakeLock=null}}
function releaseWakeLock(){const lock=wakeLock;wakeLock=null;lock?.release?.().catch?.(()=>{})}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&((state.shot&&state.shot.running)||(state.guide&&state.guide.running)))requestWakeLock()})
function toggleShot(){primeAudio();if(state.shot.running){stopShot();return}state.shot.running=true;state.shot.targetNotified=false;requestWakeLock();state.shot.interval=setInterval(()=>{state.shot.elapsed=Number.isFinite(state.shot.elapsed)?state.shot.elapsed+0.1:0.1;if(!state.shot.targetNotified&&state.shot.elapsed>=state.shot.target){state.shot.targetNotified=true;beep();vibrate();toast('Target reached — keep going or stop')}updateShotClock();},100);render()}
function updateShotClock(){const time=document.querySelector('.shot-time'),track=document.querySelector('.shot-track span');if(time)time.innerHTML=`${Number.isFinite(state.shot.elapsed)?state.shot.elapsed.toFixed(1):'0.0'}<small>s</small>`;if(track){const pct=state.shot.target>0?Math.min(100,state.shot.elapsed/state.shot.target*100):0;track.style.width=`${pct}%`}}
function stopShot(){state.shot.running=false;clearInterval(state.shot.interval);state.shot.interval=null;releaseWakeLock();render()}
function resetShot(){clearInterval(state.shot.interval);state.shot.running=false;state.shot.interval=null;state.shot.elapsed=0;state.shot.targetNotified=false;releaseWakeLock();render()}
function updateShotRatio(){const el=document.querySelector('.ratio-card strong');if(el)el.textContent=`1:${(state.shot.yield/state.shot.dose).toFixed(2)}`}
function openAuth(){if(state.user)return supabase?.auth.signOut();document.querySelector('#modal').innerHTML=`<div class="modal-backdrop"><div class="modal panel"><button class="close" id="closeModal">×</button><span class="eyebrow">YOUR COFFEE BOOK</span><h2>Make it yours.</h2><p>Save recipes and access them on any device.</p><label>Email<input id="email" type="email"></label><label>Password<input id="password" type="password" minlength="6"></label><div class="actions"><button class="primary" id="signIn">Sign in</button><button class="secondary" id="signUp">Create account</button></div></div></div>`;document.querySelector('#closeModal').onclick=closeMenu;document.querySelector('#signIn').onclick=()=>auth(false);document.querySelector('#signUp').onclick=()=>auth(true)}
async function auth(up){const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value;if(!supabase)return;const x=up?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(x.error)return toast(x.error.message);closeMenu();if(up&&!x.data.session)toast('Check your email to confirm your account.')}
function toast(m){const t=document.createElement('div');t.className='toast';t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),2600)}
async function init(){render();if(!supabase)return;const {data}=await supabase.auth.getSession();state.user=data.session?.user||null;render();await loadRecipes();supabase.auth.onAuthStateChange(async(_,s)=>{state.user=s?.user||null;render();await loadRecipes()})}
init();state.guideLoop=setInterval(tickGuide,100);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/Pocket_Barista/sw.js').catch(()=>{}));
